<?php

include 'boot.php';

$new	= $config === false;
$error	= '';

if( isset($_POST['password']) ) {
	if(empty($_POST['password']))
		$error	= 'Please input password.';
	else{
		if($new){

			$new_config	= array(
					'password' => md5($_POST['password'])
				);
			$comment	= 'This file is auto-generated by script, clear or delete this file to reset password.';
			$str	= "<?php\n" . 
					  "/**\n* $comment\n* Generated at " . date('d M Y H:i:s') . "\n */\n\n" . 
					  '$config	= ' . var_export($new_config, true) . ';';
			if(!file_put_contents('config.php', $str)){
				$error	= 'Cannot write config file, make sure config.php is writtable';
			}else{
				$_SESSION['login']	= true;
				header('Location: editor.php');
				exit;
			}
		}else{
			if(md5($_POST['password']) == $config['password']){
				// OK
				$_SESSION['login']	= true;
				header('Location: editor.php');
				exit;
			}else
			{
				$error	= 'Password not match';
			}
		}
	}
}

?><!DOCTYPE html>
<html>
<head>
	<title>AJLS Landing Page</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
 	<link href="css/style.css" rel="stylesheet">
 	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body>
<div class="row center-middle ajls-bg" style="background-size: 100% 100%;">
	<div class="col s10 m6 l4 offset-m3 offset-l4 offset-s1">
		<form method="post" class="card white-text center" style="background-color: rgba(245, 2, 2, 0.53);">
			<div class="card-content">
				<div class="card-title"><?= $new ? 'Setup new Password' : 'Login to Edit' ?></div>
				<?= $error ? "<p>$error</p>" : '<br/><br/>' ?>
				<div class="input-field">
					<input id="pass" type="text" name="password">
					<label for="pass">Password</label>
				</div>
			</div>	
			<div class="card-action red darken-4 white-text center-align">
				<button class="btn" type="submit">Login</button>
			</div>
		</form>
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
</body>
</html>